### ISSUE TITLE
Beschaffung der Grundlagendaten

### ISSUE THREAD

**Issue by ClaudiL** [tuwien-geoweb/g06-2014#14]
Ersetzen der US Zensusdaten durch die Wiener Daten (Geo-Daten und raumbezogene Sachdaten) von Open Data Wien

**Comment by ahocevar** [comment]
Hier fehlt mir noch, welche Daten ihr verwenden wollt.

**Comment by ahocevar** [comment]
Oh, hab's unter #15 gefunden. Mein obiger Kommentar ist damit hinfällig.

**Comment by ahocevar** [comment]
Ok, der Projektplan sieht schlüssig aus. Der Umsetzung steht aus meiner Sicht nichts mehr im Weg.
