### ISSUE TITLE
Graphische Überarbeitung der Applikation

### ISSUE THREAD

**Issue by ClaudiL** [tuwien-geoweb/g06-2014#21]
Symbole, Legende, popups,…

**Comment by AndreaCz** [comment]
![fahrrad](https://cloud.githubusercontent.com/assets/9860428/5678141/8377dce2-97ef-11e4-869c-5f28fa991c76.png)

**Comment by NinaNH** [comment]
![f4ceb418-97ec-11e4-94f6-0dc7efaa27ab](https://cloud.githubusercontent.com/assets/9718782/5679857/8d6c7436-9805-11e4-913b-f302b7be0c59.png)

**Comment by NinaNH** [comment]
![baum](https://cloud.githubusercontent.com/assets/9718782/5680040/b98c76d6-9807-11e4-885e-be5bc9285e89.png)

**Comment by ClaudiL** [comment]
Einfügen der neuen Symbole auf die Webseite in Dateien "censusmap_checkboxen.js" und "censusmap_checkboxen.html"

**Comment by NinaNH** [comment]
![baum](https://cloud.githubusercontent.com/assets/9718782/5680790/2b0d488a-9812-11e4-9463-9995d496c20c.png)

**Comment by NinaNH** [comment]
![buch](https://cloud.githubusercontent.com/assets/9718782/5680792/3287d1f2-9812-11e4-828a-9890046dfe66.png)

**Comment by NinaNH** [comment]
![fahrrad](https://cloud.githubusercontent.com/assets/9718782/5680793/367de648-9812-11e4-9b10-257efa007730.png)

**Comment by NinaNH** [comment]
![fussball](https://cloud.githubusercontent.com/assets/9718782/5680797/3c3ed934-9812-11e4-8f50-6ab195576f76.png)

**Comment by NinaNH** [comment]
![haltestellen](https://cloud.githubusercontent.com/assets/9718782/5680798/40cb48d4-9812-11e4-81a1-6588601345fd.png)

**Comment by NinaNH** [comment]
![universitat](https://cloud.githubusercontent.com/assets/9718782/5680800/4b1f1504-9812-11e4-8e4b-c314a3525267.png)

**Comment by NinaNH** [comment]
![spielplatz](https://cloud.githubusercontent.com/assets/9718782/5680973/20eb98b4-9814-11e4-9a84-0ef61b0c5b07.png)

**Comment by NinaNH** [comment]
![spielplatz](https://cloud.githubusercontent.com/assets/9718782/5681007/78690c70-9814-11e4-8565-18cc9bac1457.png)

**Comment by NinaNH** [comment]
![1schule](https://cloud.githubusercontent.com/assets/9718782/5702343/0efb3e4c-9a59-11e4-9d88-ed5b9ecb5224.png)

**Comment by NinaNH** [comment]
![1schule](https://cloud.githubusercontent.com/assets/9718782/5702422/5a596764-9a5a-11e4-9cc7-e0c54883b7dc.png)

**Comment by NinaNH** [comment]
![1schule_klein](https://cloud.githubusercontent.com/assets/9718782/5702554/dad22b5a-9a5b-11e4-9189-45cad967981d.png)

**Comment by NinaNH** [comment]
![2spielplatz](https://cloud.githubusercontent.com/assets/9718782/5702710/65b04274-9a5d-11e4-8484-ac290f232ade.png)

**Comment by NinaNH** [comment]
![3haltestellen](https://cloud.githubusercontent.com/assets/9718782/5702712/6ce678b0-9a5d-11e4-9c26-22a44aea13ea.png)

**Comment by NinaNH** [comment]
![4fahrradplatze](https://cloud.githubusercontent.com/assets/9718782/5702714/70cb2674-9a5d-11e4-9465-11cbfc8fe7b9.png)

**Comment by NinaNH** [comment]
![5sportstatten](https://cloud.githubusercontent.com/assets/9718782/5702718/73d71ad0-9a5d-11e4-8987-0eb33cdcb922.png)

**Comment by NinaNH** [comment]
![6park](https://cloud.githubusercontent.com/assets/9718782/5702720/7767bb5a-9a5d-11e4-9577-b40263281ec2.png)

**Comment by NinaNH** [comment]
![7universitat](https://cloud.githubusercontent.com/assets/9718782/5702722/7a5f5ce6-9a5d-11e4-8074-ecde4ace1b3e.png)
