### ISSUE TITLE
Kontrolle auf Fehler inklusive Behebung 

### ISSUE THREAD

**Issue by ClaudiL** [tuwien-geoweb/g06-2014#26]
Verlinkungen, Korrekturlesen, Kontrolle der Darstellung auf mobilen Geräten, …

**Comment by ClaudiL** [comment]
Restliche Texte ausformulieren

**Comment by AndreaCz** [comment]
@ahocevar 
Es funktionieren alle Checkboxen bis auf die Haltestellen. Hier werden keine angezeigt. Wir haben alles kontrolliert und konnten keinen Fehler finden.
Können Sie uns vielleicht einen Hinweis geben wie es zu lösen ist?

**Comment by ahocevar** [comment]
Könnt ihr mir eine URL zum Testen geben?

**Comment by NinaNH** [comment]
Meinen Sie die URL zu unserer App? 

http://student.ifip.tuwien.ac.at/geoweb/2014/g06/homepage/projekt_wien.htm

**Comment by ahocevar** [comment]
Tippfehler in Zeile 138 in `censusmap_checkboxen.js`: ihr habt dort `haltstellen` statt `haltestellen`.

**Comment by AndreaCz** [comment]
Der Fehler wurde behoben. Es funktioniert leider noch immer nicht richtig. Es werden zwar Haltestellen angezeigt, jedoch nicht alle

**Comment by ahocevar** [comment]
In der URL für euren Haltestellen-Layer steht noch `&maxFeatures=500`. Es werden also nur 500 Haltestellen geladen. Entfernt diese Einschränkung also einfach aus der URL.

**Comment by AndreaCz** [comment]
Vielen Dank für die Hilfe!
