### ISSUE TITLE
Fehler - bitte um Hilfe

### ISSUE THREAD

**Issue by ClaudiL** [tuwien-geoweb/g06-2014#29]
@ahocevar 

Wir haben jetzt eine .html und eine .js Datei angelegt mit den Zensusdaten von Wien. 
Zusätzlich wollten wir mit checkboxen Layer von OGD Wien einfügen. Allerdings passiert nichts wenn man eine Checkbox anklickt, obwohl wir eigentlich passende Funktionen in unserer censusmap_checkboxen.js Datei drinnen haben.

Können Sie uns vielleicht einen Hinweis geben, wie wir das lösen könnten?

**Comment by ahocevar** [comment]
In eurem Datenspeicher waren Schema und Passwort eingetragen. Das habe ich gelöscht, und jetzt werden eure OGD-Layer angezeigt.

**Comment by NinaNH** [comment]
Dankeschön! :)
