### ISSUE TITLE
Link auf Startseite zu neuer Map hinzufügen

### ISSUE THREAD

**Issue by ClaudiL** [tuwien-geoweb/g06-2014#8]

**Comment by ClaudiL** [comment]
Abgabe erfolgt
@ahocevar

**Comment by ahocevar** [comment]
Danke! Ein Teil der Aufgabe fehlt noch: beim Zentrieren auf die Position von ol.Geolocation wird noch immer setCenter verwendet, und noch nicht fitGeometry auf die accuracyGeometry. Wollt ihr das noch nachbessern?
